# Generated by Django 3.0.1 on 2019-12-23 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matatu', '0002_auto_20191223_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='rte_Destination2',
            field=models.CharField(choices=[('bmr kisauni', 'Bamburi Kisauni'), ('bmr mtambo', 'Bamburi Mtambo'), ('tdr', 'Tudor'), ('nyl', 'Nyali'), ('mtw', 'Mtwapa'), ('mjn', 'Majengo'), ('mgn', 'Magongo'), ('dks', 'Docks'), ('mrn', 'Mshomoroni'), ('kng', 'Kongowea')], max_length=11),
        ),
    ]
