# Generated by Django 3.0.1 on 2019-12-23 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matatu', '0003_auto_20191223_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='rte_Destination1',
            field=models.CharField(choices=[('bmr', 'Bamburi'), ('tdr', 'Tudor'), ('nyl', 'Nyali'), ('mtw', 'Mtwapa'), ('mjn', 'Majengo'), ('mgn', 'Magongo'), ('dks', 'Docks'), ('mrn', 'Mshomoroni'), ('kng', 'Kongowea')], max_length=11),
        ),
        migrations.AlterField(
            model_name='route',
            name='rte_Destination2',
            field=models.CharField(choices=[('bmr', 'Bamburi'), ('tdr', 'Tudor'), ('nyl', 'Nyali'), ('mtw', 'Mtwapa'), ('mjn', 'Majengo'), ('mgn', 'Magongo'), ('dks', 'Docks'), ('mrn', 'Mshomoroni'), ('kng', 'Kongowea')], max_length=11),
        ),
        migrations.AlterField(
            model_name='route',
            name='rte_via',
            field=models.CharField(blank=True, choices=[('kisauni', 'Kisauni'), ('mtambo', 'Mtamboni'), ('bmbl', 'Bombolulu')], max_length=10),
        ),
    ]
