# Generated by Django 3.0.1 on 2019-12-23 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matatu', '0004_auto_20191223_1055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='rte_Name',
        ),
    ]
