# Generated by Django 2.2.7 on 2019-11-09 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Duty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dty_name', models.CharField(max_length=100)),
                ('dty_description', models.TextField(max_length=350)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rte_Name', models.CharField(max_length=100)),
                ('rte_Destination1', models.CharField(max_length=100)),
                ('rte_Destination2', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Saccos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sacco_name', models.CharField(max_length=100)),
                ('sacco_ID', models.CharField(max_length=100)),
                ('sacco_HQ', models.CharField(max_length=100)),
                ('sacco_Leader', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Crew',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crw_fName', models.CharField(max_length=100)),
                ('crw_lName', models.CharField(max_length=100)),
                ('crw_Location', models.CharField(max_length=100)),
                ('crw_Phone', models.CharField(max_length=100)),
                ('crw_Duty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.Duty')),
            ],
        ),
    ]
