# Generated by Django 2.2.7 on 2019-11-09 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='crew',
            options={'verbose_name_plural': 'The Crew'},
        ),
        migrations.AlterModelOptions(
            name='duty',
            options={'verbose_name_plural': 'Crew Duties'},
        ),
        migrations.AlterModelOptions(
            name='route',
            options={'verbose_name_plural': 'Available Routes'},
        ),
        migrations.AlterModelOptions(
            name='saccos',
            options={'verbose_name_plural': 'The Sacco'},
        ),
        migrations.AddField(
            model_name='route',
            name='rte_via',
            field=models.CharField(default='', max_length=100),
        ),
    ]
